version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    links:
      - postgres
      - adminer
    build: ./backend/
    restart: always
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate core &&
             python manage.py migrate music &&
             python manage.py migrate playlist &&
             python manage.py migrate favorites &&
             python manage.py migrate user &&
             python manage.py migrate album &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"

volumes:
  pgdata:
