version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"

#  backend:
#    depends_on:
#      - db
#    build: ./settings
    