# Generated by Django 4.1.6 on 2023-02-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_performer',
            field=models.BooleanField(default=False, verbose_name='Исполнитель'),
        ),
    ]
