# Generated by Django 4.1.6 on 2023-02-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_is_performer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_performer',
        ),
        migrations.AddField(
            model_name='profile',
            name='type_user',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Обычный пользователь'), (2, 'Исполнитель')], default=1, verbose_name='Тип профиля'),
        ),
    ]
