# Generated by Django 4.1.6 on 2023-02-20 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_is_performer_profile_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg'])], verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.BooleanField(default=False, verbose_name='Исполнитель?'),
        ),
    ]
