# Generated by Django 4.1.6 on 2023-02-06 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='upload_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
