# Generated by Django 4.1.6 on 2023-02-06 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_genre_alter_music_upload_by_music_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='music',
            name='upload_by',
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='music',
            name='upload_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
